// Generated by the protocol buffer compiler.  DO NOT EDIT!

package cn.com.jsj.lib_base.nano;

import cn.com.jsj.lib_common.netcore.bean.ParcelableMessageNano;
import cn.com.jsj.lib_common.netcore.bean.ParcelableMessageNanoCreator;

@SuppressWarnings("hiding")
public final class BaseResponse_p extends
        ParcelableMessageNano {

  // Used by Parcelable
  @SuppressWarnings({"unused"})
  public static final Creator<BaseResponse_p> CREATOR =
      new ParcelableMessageNanoCreator<
                BaseResponse_p>(BaseResponse_p.class);

  private static volatile BaseResponse_p[] _emptyArray;
  public static BaseResponse_p[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new BaseResponse_p[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional bool IsSuccess = 1 [default = false];
  public boolean isSuccess;

  // optional string ErrorMessage = 2;
  public String errorMessage;

  // optional string ErrorCode = 3;
  public String errorCode;

  public BaseResponse_p() {
    clear();
  }

  public BaseResponse_p clear() {
    isSuccess = false;
    errorMessage = "";
    errorCode = "";
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.isSuccess != false) {
      output.writeBool(1, this.isSuccess);
    }
    if (!this.errorMessage.equals("")) {
      output.writeString(2, this.errorMessage);
    }
    if (!this.errorCode.equals("")) {
      output.writeString(3, this.errorCode);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.isSuccess != false) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeBoolSize(1, this.isSuccess);
    }
    if (!this.errorMessage.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.errorMessage);
    }
    if (!this.errorCode.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(3, this.errorCode);
    }
    return size;
  }

  @Override
  public BaseResponse_p mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 8: {
          this.isSuccess = input.readBool();
          break;
        }
        case 18: {
          this.errorMessage = input.readString();
          break;
        }
        case 26: {
          this.errorCode = input.readString();
          break;
        }
      }
    }
  }

  public static BaseResponse_p parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new BaseResponse_p(), data);
  }

  public static BaseResponse_p parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new BaseResponse_p().mergeFrom(input);
  }
}
