// Generated by the protocol buffer compiler.  DO NOT EDIT!

package cn.com.jsj.lib_base.nano;

import cn.com.jsj.lib_common.netcore.bean.ParcelableMessageNano;
import cn.com.jsj.lib_common.netcore.bean.ParcelableMessageNanoCreator;

@SuppressWarnings("hiding")
public final class RcBaseRequest extends
        ParcelableMessageNano {

  // Used by Parcelable
  @SuppressWarnings({"unused"})
  public static final Creator<RcBaseRequest> CREATOR =
      new ParcelableMessageNanoCreator<
                RcBaseRequest>(RcBaseRequest.class);

  private static volatile RcBaseRequest[] _emptyArray;
  public static RcBaseRequest[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new RcBaseRequest[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional string AppVersion = 1;
  public String appVersion;

  // optional .SourceWay SourceWay = 2 [default = SourceWayNoSetting];
  public int sourceWay;

  // optional .LanguageVersion ClientLanugage = 3 [default = CN];
  public int clientLanugage;

  // optional string SDKVersion = 4;
  public String sDKVersion;

  // optional .AppSource AppSource = 5 [default = NoSetting];
  public int appSource;

  public RcBaseRequest() {
    clear();
  }

  public RcBaseRequest clear() {
    appVersion = "";
    sourceWay = SourceWay.SourceWayNoSetting;
    clientLanugage = LanguageVersion.CN;
    sDKVersion = "";
    appSource = AppSource.NoSetting;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (!this.appVersion.equals("")) {
      output.writeString(1, this.appVersion);
    }
    if (this.sourceWay != SourceWay.SourceWayNoSetting) {
      output.writeInt32(2, this.sourceWay);
    }
    if (this.clientLanugage != LanguageVersion.CN) {
      output.writeInt32(3, this.clientLanugage);
    }
    if (!this.sDKVersion.equals("")) {
      output.writeString(4, this.sDKVersion);
    }
    if (this.appSource != AppSource.NoSetting) {
      output.writeInt32(5, this.appSource);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (!this.appVersion.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.appVersion);
    }
    if (this.sourceWay != SourceWay.SourceWayNoSetting) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeInt32Size(2, this.sourceWay);
    }
    if (this.clientLanugage != LanguageVersion.CN) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeInt32Size(3, this.clientLanugage);
    }
    if (!this.sDKVersion.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(4, this.sDKVersion);
    }
    if (this.appSource != AppSource.NoSetting) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeInt32Size(5, this.appSource);
    }
    return size;
  }

  @Override
  public RcBaseRequest mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          this.appVersion = input.readString();
          break;
        }
        case 16: {
          int value = input.readInt32();
          switch (value) {
            case SourceWay.SourceWayNoSetting:
            case SourceWay.Web:
            case SourceWay.Wap:
            case SourceWay.IOS:
            case SourceWay.Android:
            case SourceWay.CRM_p:
            case SourceWay.BusinessTravel:
            case SourceWay.WeChat:
            case SourceWay.WeChatProgram:
              this.sourceWay = value;
              break;
          }
          break;
        }
        case 24: {
          int value = input.readInt32();
          switch (value) {
            case LanguageVersion.CN:
            case LanguageVersion.EN:
              this.clientLanugage = value;
              break;
          }
          break;
        }
        case 34: {
          this.sDKVersion = input.readString();
          break;
        }
        case 40: {
          int value = input.readInt32();
          switch (value) {
            case AppSource.NoSetting:
            case AppSource.AirwayKeeper:
            case AppSource.Jsj:
            case AppSource.Crm:
              this.appSource = value;
              break;
          }
          break;
        }
      }
    }
  }

  public static RcBaseRequest parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new RcBaseRequest(), data);
  }

  public static RcBaseRequest parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new RcBaseRequest().mergeFrom(input);
  }
}
