// Generated by the protocol buffer compiler.  DO NOT EDIT!

package cn.com.jsj.lib_base.nano;

// enum SourceApp_p
public interface SourceApp_p {
  public static final int SourceAppNoSetting_p = 0;
  public static final int GoldenCentury_p = 1;
  public static final int AirwayKeeper_p = 2;
  public static final int TrainTicket_p = 3;
}
